# Generated by Django 6.0.4 on 2026-05-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='title',
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
