# Generated by Django 6.0.4 on 2026-05-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_auctionlistings_title_auctionlistings_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='bid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
