# Generated by Django 6.0.4 on 2026-06-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlistings_id_alter_bids_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
    ]
