# Generated by Django 6.0.4 on 2026-06-23 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_listing_id_comments_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='closing_bid',
            field=models.ForeignKey(default=django.db.models.deletion.SET_NULL, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.bids'),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='winning_user',
            field=models.ForeignKey(default=django.db.models.deletion.SET_NULL, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Auction_Winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='publisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Auction_Publisher', to=settings.AUTH_USER_MODEL),
        ),
    ]
