# Generated by Django 6.0.4 on 2026-06-23 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auctionlistings_closing_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='closing_bid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.bids'),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='winning_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Auction_Winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
